### PR TITLE
DHCP option 234 feature

### LINKED ISSUE #513: :sparkles: Add custom DHCP option 234 in Kea Config
### User Story

As a… Developer
I want Admin Portal app to… add custom DHCP option 234 def and data in the config file for Kea
So that… Whenever a new config gets generated, the new custom DHCP option is always present for all subnets

### Value / Purpose

This new feature enables the MoJ OFFICIAL EUC devices to better share application and Windows Update payloads across the local site network without going out to the WAN and Internet.

### Useful Contacts

Matt White, Chandra Singh, Charlie Coverdale

### Additional Information

_No response_

### Definition of Done

Example
- [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

### PR DESCRIPTION
**Pull request by mitchdawson1982**
# What
DHCP Option 234 feature is a request from the EUC Team.
This option 234 will be used by dhcp clients to optimise Windows updates delivery. All clients in a single site with same data for option 234 will share Windows updates to reduce the load on the WLAN.
 - A custom dhcp option with id 234 is defined at the top of the config
 - All sites will have a UUID by default
 - A new toggle button is added to site to enable `Delivery Optimisation`
 - When that button is toggled for a pre existing site, a UUID will be generated and DHCP option data will be populated in the option config for all the subnets in that site.  

Closes #513  

## Screenshots
Screenshot 2022-05-30 at 15 55 28
Screenshot 2022-05-30 at 15 55 47
Screenshot 2022-05-30 at 15 55 52
Screenshot 2022-05-30 at 15 56 06

### CODE REVIEW

**Review by mTouhid — CHANGES_REQUESTED** [review]
@mitchdawson1982, I have added few inline comments and everything else LGTM. 👍🏼

**Comment by wanieldilson** [comment]
@mTouhid can we add the screenshots to the PR so @MatthewWhiteMoJ and co can have a look?

**Review by mTouhid — APPROVED** [review]
LGTM

**Comment by MatthewWhiteMoJ** [comment]
looks good - is the default option that the feature is enabled and then turned off if not required?

**Comment by wanieldilson** [comment]
> 

Bit of background, every site will have a UUID _generated_ and ready to use (disabled by default).  _Enabling_ the feature manipulates the config file adding option 234 to all subnets in that site.

**Review by MatthewWhiteMoJ — APPROVED** [review]
LGTM - not that i fully understand all the code changes but Dan's explanation looks good

**Pull request merged**
